server:
  port: 8080
  servlet:
    context-path: /demo

spring:
  application:
    name: demo
  h2:
    console:
      enabled: true
      path: /h2-console
      settings.trace: false
      settings.web-allow-others: false
  datasource:
    url: jdbc:h2:mem:mydb;TIME ZONE=UTC
    username: demoUser
    password: demoPassword
    driverClassName: org.h2.Driver
    initialization-mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none