CREATE TABLE PRODUCTS (
ID INT NOT NULL,
BRAND_ID INT NOT NULL,
START_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
END_DATE TIMESTAMP WITH TIME ZONE NOT NULL,
PRICE_LIST INT NOT NULL,
PRODUCT_ID INT NOT NULL,
PRIORITY INT NOT NULL,
PRICE FLOAT NOT NULL,
CURR VARCHAR NOT NULL,
PRIMARY KEY ( ID )
);